;; -*- mode: eask; lexical-binding: t -*-

(package "treesit-sexp"
         "0.1.0"
         "Tree-sitter based s-expression navigation")

(keywords "convenience" "lisp" "tools")

(package-file "treesit-sexp.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "29.1")

(development
 (depends-on "ellsp"))
